[theme]
primaryColor = "#0d7377"
backgroundColor = "#f7f7f4"
secondaryBackgroundColor = "#eef0ea"
textColor = "#32444f"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
