[theme]
primaryColor = "#FF4713"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F8F8"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
